// All data for projects and people

const projects = [
    // Company Projects
    {
        id: 'proj-1',
        title: 'StartechOne Platform',
        description: 'A comprehensive learning management system for tech education with real-time collaboration features, progress tracking, and interactive coding challenges.',
        category: 'website',
        isCompanyProject: true,
        imageUrl: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['React', 'Node.js', 'PostgreSQL', 'WebSocket', 'TypeScript'],
        githubUrl: 'https://github.com/startechone/platform',
        liveUrl: 'https://platform.startechone.com',
        createdAt: '2024-01-15',
    },
    {
        id: 'proj-2',
        title: 'Analytics Dashboard Pro',
        description: 'Advanced data visualization platform for business intelligence with custom chart builders, real-time data streams, and predictive analytics powered by machine learning.',
        category: 'data-analysis',
        isCompanyProject: true,
        imageUrl: 'https://images.unsplash.com/photo-1759661966728-4a02e3c6ed91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Python', 'D3.js', 'React', 'TensorFlow', 'Apache Kafka'],
        githubUrl: 'https://github.com/startechone/analytics-pro',
        liveUrl: 'https://analytics.startechone.com',
        createdAt: '2024-03-20',
    },
    {
        id: 'proj-3',
        title: 'Mobile Learning App',
        description: 'Cross-platform mobile application for on-the-go learning with offline support, gamification, and personalized learning paths.',
        category: 'mobile-app',
        isCompanyProject: true,
        imageUrl: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['React Native', 'Firebase', 'Redux', 'SQLite'],
        githubUrl: 'https://github.com/startechone/mobile-app',
        liveUrl: 'https://apps.apple.com/startechone',
        createdAt: '2024-02-10',
    },
    // Student Projects
    {
        id: 'proj-4',
        title: 'E-Commerce Platform',
        description: 'Full-featured online shopping platform with payment integration, inventory management, and admin dashboard. Built as a capstone project.',
        category: 'website',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Next.js', 'Stripe', 'MongoDB', 'Tailwind CSS'],
        githubUrl: 'https://github.com/student/ecommerce-platform',
        liveUrl: 'https://ecommerce-demo.vercel.app',
        createdBy: 'Sarah Johnson',
        createdAt: '2024-05-12',
    },
    {
        id: 'proj-5',
        title: 'Weather Prediction Model',
        description: 'Machine learning model for weather forecasting using historical data and real-time API integration. Achieves 85% accuracy.',
        category: 'data-analysis',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1759661966728-4a02e3c6ed91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Python', 'Scikit-learn', 'Pandas', 'Flask'],
        githubUrl: 'https://github.com/student/weather-ml',
        createdBy: 'Michael Chen',
        createdAt: '2024-06-08',
    },
    {
        id: 'proj-6',
        title: 'Task Management System',
        description: 'Collaborative project management tool with real-time updates, team chat, and advanced filtering capabilities.',
        category: 'website',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Vue.js', 'Supabase', 'Vuetify', 'WebSocket'],
        githubUrl: 'https://github.com/student/task-manager',
        liveUrl: 'https://task-manager-demo.vercel.app',
        createdBy: 'Emily Rodriguez',
        createdAt: '2024-04-22',
    },
    {
        id: 'proj-7',
        title: 'Fitness Tracker AI',
        description: 'Mobile app with AI-powered workout recommendations, progress tracking, and nutrition planning.',
        category: 'mobile-app',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['React Native', 'TensorFlow Lite', 'Firebase'],
        githubUrl: 'https://github.com/student/fitness-ai',
        createdBy: 'David Kim',
        createdAt: '2024-07-15',
    },
    {
        id: 'proj-8',
        title: 'Customer Sentiment Analysis',
        description: 'NLP-based tool for analyzing customer reviews and social media sentiment with interactive dashboards.',
        category: 'ai-ml',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1697577418970-95d99b5a55cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Python', 'NLTK', 'Transformers', 'Streamlit'],
        githubUrl: 'https://github.com/student/sentiment-analysis',
        liveUrl: 'https://sentiment-analyzer.streamlit.app',
        createdBy: 'Priya Patel',
        createdAt: '2024-08-03',
    },
    {
        id: 'proj-9',
        title: 'Portfolio Generator',
        description: 'Automated portfolio website generator with multiple templates, dark mode, and easy customization.',
        category: 'website',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
        githubUrl: 'https://github.com/student/portfolio-gen',
        liveUrl: 'https://portfolio-gen.vercel.app',
        createdBy: 'James Wilson',
        createdAt: '2024-09-10',
    },
    {
        id: 'proj-10',
        title: 'Sales Forecasting Dashboard',
        description: 'Interactive dashboard for sales prediction using time series analysis and visualization.',
        category: 'data-analysis',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1759661966728-4a02e3c6ed91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['Python', 'Prophet', 'Plotly', 'Dash'],
        githubUrl: 'https://github.com/student/sales-forecast',
        createdBy: 'Lisa Anderson',
        createdAt: '2024-10-18',
    },
    {
        id: 'proj-11',
        title: 'Code Snippet Manager',
        description: 'Browser extension for saving, organizing, and sharing code snippets with syntax highlighting.',
        category: 'other',
        isCompanyProject: false,
        imageUrl: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        technologies: ['JavaScript', 'Chrome API', 'IndexedDB'],
        githubUrl: 'https://github.com/student/snippet-manager',
        createdBy: 'Alex Thompson',
        createdAt: '2024-11-05',
    },
];

const people = [
    // Staff
    {
        id: 'person-1',
        name: 'Dr. Jennifer Martinez',
        role: 'staff',
        title: 'Chief Technology Officer',
        bio: 'With over 15 years of experience in tech education and software development, Dr. Martinez leads our technical strategy and curriculum development.',
        imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
        githubUrl: 'https://github.com/jmartinez',
        linkedinUrl: 'https://linkedin.com/in/jennifer-martinez',
        portfolioUrl: 'https://jmartinez.dev',
        skills: ['Software Architecture', 'React', 'Node.js', 'Python', 'Cloud Computing'],
    },
    {
        id: 'person-2',
        name: 'Robert Chen',
        role: 'staff',
        title: 'Lead Data Science Instructor',
        bio: 'Former data scientist at major tech companies, Robert brings real-world experience in machine learning and analytics to our students.',
        imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        githubUrl: 'https://github.com/rchen',
        linkedinUrl: 'https://linkedin.com/in/robert-chen',
        skills: ['Machine Learning', 'Python', 'Data Analysis', 'TensorFlow', 'SQL'],
    },
    {
        id: 'person-3',
        name: 'Amanda Foster',
        role: 'staff',
        title: 'Senior Frontend Developer & Instructor',
        bio: 'Amanda specializes in modern web development and has mentored hundreds of students in building beautiful, accessible web applications.',
        imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
        githubUrl: 'https://github.com/afoster',
        linkedinUrl: 'https://linkedin.com/in/amanda-foster',
        portfolioUrl: 'https://amandafoster.dev',
        skills: ['React', 'TypeScript', 'CSS', 'UI/UX Design', 'Accessibility'],
    },
    {
        id: 'person-4',
        name: 'Marcus Johnson',
        role: 'staff',
        title: 'Mobile Development Lead',
        bio: 'Expert in cross-platform mobile development with a passion for creating intuitive user experiences.',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        githubUrl: 'https://github.com/mjohnson',
        linkedinUrl: 'https://linkedin.com/in/marcus-johnson',
        skills: ['React Native', 'iOS', 'Android', 'Flutter', 'Mobile UX'],
    },
    // Students
    {
        id: 'person-5',
        name: 'Sarah Johnson',
        role: 'student',
        title: 'Full Stack Development Student',
        bio: 'Passionate about building scalable web applications. Currently working on e-commerce solutions and payment integrations.',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        githubUrl: 'https://github.com/sarahjohnson',
        linkedinUrl: 'https://linkedin.com/in/sarah-johnson',
        portfolioUrl: 'https://sarahjohnson.dev',
        skills: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Stripe API'],
    },
    {
        id: 'person-6',
        name: 'Michael Chen',
        role: 'student',
        title: 'Data Science Student',
        bio: 'Focused on machine learning and predictive analytics. Interested in applying AI to solve real-world problems.',
        imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        githubUrl: 'https://github.com/michaelchen',
        linkedinUrl: 'https://linkedin.com/in/michael-chen',
        skills: ['Python', 'Machine Learning', 'Data Visualization', 'Scikit-learn', 'Pandas'],
    },
    {
        id: 'person-7',
        name: 'Emily Rodriguez',
        role: 'student',
        title: 'Frontend Development Student',
        bio: 'Creating beautiful and functional user interfaces. Love working with Vue.js and modern CSS frameworks.',
        imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        githubUrl: 'https://github.com/emilyrodriguez',
        linkedinUrl: 'https://linkedin.com/in/emily-rodriguez',
        portfolioUrl: 'https://emilyrodriguez.dev',
        skills: ['Vue.js', 'JavaScript', 'CSS', 'Vuetify', 'Figma'],
    },
    {
        id: 'person-8',
        name: 'David Kim',
        role: 'student',
        title: 'Mobile Development Student',
        bio: 'Building cross-platform mobile apps with a focus on performance and user experience.',
        imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
        githubUrl: 'https://github.com/davidkim',
        linkedinUrl: 'https://linkedin.com/in/david-kim',
        skills: ['React Native', 'Firebase', 'Redux', 'iOS', 'Android'],
    },
    {
        id: 'person-9',
        name: 'Priya Patel',
        role: 'student',
        title: 'AI/ML Student',
        bio: 'Exploring natural language processing and computer vision. Working on sentiment analysis projects.',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
        githubUrl: 'https://github.com/priyapatel',
        linkedinUrl: 'https://linkedin.com/in/priya-patel',
        skills: ['Python', 'NLP', 'TensorFlow', 'Computer Vision', 'Deep Learning'],
    },
    {
        id: 'person-10',
        name: 'James Wilson',
        role: 'student',
        title: 'Web Development Student',
        bio: 'Specializing in modern frontend technologies and building tools that help other developers.',
        imageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400',
        githubUrl: 'https://github.com/jameswilson',
        portfolioUrl: 'https://jameswilson.dev',
        skills: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Git'],
    },
    {
        id: 'person-11',
        name: 'Lisa Anderson',
        role: 'student',
        title: 'Data Analytics Student',
        bio: 'Data enthusiast focused on business intelligence and predictive modeling.',
        imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
        githubUrl: 'https://github.com/lisaanderson',
        linkedinUrl: 'https://linkedin.com/in/lisa-anderson',
        skills: ['Python', 'SQL', 'Data Visualization', 'Time Series', 'Tableau'],
    },
    {
        id: 'person-12',
        name: 'Alex Thompson',
        role: 'student',
        title: 'Software Development Student',
        bio: 'Building practical tools and extensions. Interested in browser APIs and developer productivity.',
        imageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
        githubUrl: 'https://github.com/alexthompson',
        portfolioUrl: 'https://alexthompson.dev',
        skills: ['JavaScript', 'Chrome Extensions', 'Web APIs', 'IndexedDB', 'Git'],
    },
];
